# Generated by Django 5.0.6 on 2026-06-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
