# Generated by Django 5.0.6 on 2026-09-15 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_external_fields_to_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'واحد', 'verbose_name_plural': 'واحدها'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'سازمان', 'verbose_name_plural': 'سازمان\u200cها'},
        ),
        migrations.AddField(
            model_name='department',
            name='invite_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ساخت دعوت'),
        ),
        migrations.AddField(
            model_name='department',
            name='invite_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='توکن دعوت'),
        ),
        migrations.AddField(
            model_name='department',
            name='invite_used',
            field=models.BooleanField(default=False, verbose_name='استفاده شده'),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('active', 'فعال'), ('inactive', 'غیرفعال')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='organization',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید'),
        ),
        migrations.AddField(
            model_name='organization',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_organizations', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده'),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تأیید'), ('active', 'فعال'), ('rejected', 'رد شده'), ('suspended', 'معلق')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('organization', 'code')},
        ),
    ]
