# Generated by Django 5.0.6 on 2026-06-21 23:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('manufacturing', 'تولیدی'), ('service', 'خدماتی'), ('rto', 'RTO'), ('holding', 'هلدینگ')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('asset_type', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('discovered_by', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('potential_value', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='discovery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('technological', 'فناورانه'), ('knowledge', 'دانشی'), ('relational', 'ارتباطی'), ('human', 'انسانی'), ('structural', 'ساختاری')], max_length=20)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('classification_date', models.DateField(auto_now_add=True)),
                ('discovery_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='intangible_assets.discoveryform')),
            ],
        ),
        migrations.CreateModel(
            name='AssetListForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_date', models.DateField(auto_now_add=True)),
                ('total_count', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('discovery_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_lists', to='intangible_assets.discoveryform')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_name', models.CharField(max_length=255)),
                ('expert_position', models.CharField(max_length=255)),
                ('interview_date', models.DateField()),
                ('tacit_knowledge', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('discovery_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='intangible_assets.discoveryform')),
            ],
        ),
        migrations.CreateModel(
            name='HiddenAssetChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_documented', models.BooleanField(default=False)),
                ('is_in_use', models.BooleanField(default=False)),
                ('has_expert', models.BooleanField(default=False)),
                ('has_market_value', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('discovery_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_checklists', to='intangible_assets.discoveryform')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('q1', models.IntegerField(default=3)),
                ('q2', models.IntegerField(default=3)),
                ('q3', models.IntegerField(default=3)),
                ('q4', models.IntegerField(default=3)),
                ('q5', models.IntegerField(default=3)),
                ('q6', models.IntegerField(default=3)),
                ('q7', models.IntegerField(default=3)),
                ('q8', models.IntegerField(default=3)),
                ('q9', models.IntegerField(default=3)),
                ('q10', models.IntegerField(default=3)),
                ('q11', models.IntegerField(default=3)),
                ('q12', models.IntegerField(default=3)),
                ('q13', models.IntegerField(default=3)),
                ('q14', models.IntegerField(default=3)),
                ('q15', models.IntegerField(default=3)),
                ('q16', models.IntegerField(default=3)),
                ('q17', models.IntegerField(default=3)),
                ('q18', models.IntegerField(default=3)),
                ('q19', models.IntegerField(default=3)),
                ('q20', models.IntegerField(default=3)),
                ('total_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('verified', 'تأیید شده'), ('pending', 'در انتظار'), ('rejected', 'رد شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreliminaryEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('confidence_level', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('evaluator', models.CharField(max_length=255)),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('discovery_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='intangible_assets.discoveryform')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(default='دارایی بدون نام', max_length=255)),
                ('asset_uid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('category', models.CharField(default='unknown', max_length=50)),
                ('result', models.CharField(choices=[('confirmed', 'دارایی قطعی'), ('conditional', 'مشروط'), ('rejected', 'رد شده')], default='confirmed', max_length=20)),
                ('discovery_date', models.DateField(blank=True, null=True)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('strategic_economic', 'استراتژیک - اقتصادی'), ('strategic_social', 'استراتژیک - اجتماعی'), ('strategic_knowledge', 'استراتژیک - دانشی'), ('strategic_cultural', 'استراتژیک - فرهنگی'), ('strategic_environmental', 'استراتژیک - زیست\u200cمحیطی'), ('operational_economic', 'عملیاتی - اقتصادی'), ('operational_social', 'عملیاتی - اجتماعی'), ('operational_knowledge', 'عملیاتی - دانشی'), ('operational_cultural', 'عملیاتی - فرهنگی'), ('operational_environmental', 'عملیاتی - زیست\u200cمحیطی'), ('support_economic', 'پشتیبان - اقتصادی'), ('support_social', 'پشتیبان - اجتماعی'), ('support_knowledge', 'پشتیبان - دانشی'), ('support_cultural', 'پشتیبان - فرهنگی'), ('support_environmental', 'پشتیبان - زیست\u200cمحیطی')], max_length=50)),
                ('default_result', models.CharField(choices=[('confirmed', 'دارایی قطعی'), ('conditional', 'مشروط'), ('rejected', 'رد شده')], default='confirmed', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('condition_1_non_physical', models.BooleanField(default=True)),
                ('condition_2_identifiable', models.BooleanField(default=True)),
                ('condition_3_controllable', models.BooleanField(default=True)),
                ('condition_4_value_creating', models.BooleanField(default=True)),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='intangible_assets.organizationtype')),
            ],
        ),
        migrations.CreateModel(
            name='TacitKnowledgeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_title', models.CharField(max_length=255)),
                ('knowledge_description', models.TextField()),
                ('source_person', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discovery_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tacit_knowledge', to='intangible_assets.discoveryform')),
            ],
        ),
    ]
