# Generated by Django 5.0.6 on 2026-06-15 17:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=255, verbose_name='نام دارایی')),
                ('asset_code', models.CharField(max_length=50, unique=True, verbose_name='کد دارایی')),
                ('asset_type', models.CharField(choices=[('knowledge', 'دانشی'), ('experiential', 'تجربی'), ('technological', 'فناورانه'), ('tacit', 'ضمنی'), ('hidden', 'پنهان')], max_length=20, verbose_name='نوع دارایی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('discovered_by', models.CharField(max_length=255, verbose_name='کشف شده توسط')),
                ('department', models.CharField(max_length=255, verbose_name='واحد سازمانی')),
                ('potential_value', models.TextField(verbose_name='ارزش بالقوه')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='discovery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('technological', 'فناورانه'), ('knowledge', 'دانشی'), ('relational', 'ارتباطی'), ('human', 'انسانی'), ('structural', 'ساختاری')], max_length=20)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('classification_date', models.DateField(auto_now_add=True)),
                ('discovery_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='intangible_assets.discoveryform')),
            ],
        ),
        migrations.CreateModel(
            name='AssetListForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_date', models.DateField(auto_now_add=True)),
                ('total_count', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('discovery_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_lists', to='intangible_assets.discoveryform')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert_name', models.CharField(max_length=255)),
                ('expert_position', models.CharField(max_length=255)),
                ('interview_date', models.DateField()),
                ('tacit_knowledge', models.TextField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('discovery_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='intangible_assets.discoveryform')),
            ],
        ),
        migrations.CreateModel(
            name='HiddenAssetChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_documented', models.BooleanField(default=False)),
                ('is_in_use', models.BooleanField(default=False)),
                ('has_expert', models.BooleanField(default=False)),
                ('has_market_value', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('discovery_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_checklists', to='intangible_assets.discoveryform')),
            ],
        ),
        migrations.CreateModel(
            name='PreliminaryEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('confidence_level', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('evaluator', models.CharField(max_length=255)),
                ('evaluation_date', models.DateField(auto_now_add=True)),
                ('discovery_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='intangible_assets.discoveryform')),
            ],
        ),
        migrations.CreateModel(
            name='TacitKnowledgeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_title', models.CharField(max_length=255)),
                ('knowledge_description', models.TextField()),
                ('source_person', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discovery_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tacit_knowledge', to='intangible_assets.discoveryform')),
            ],
        ),
    ]
