# Generated by Django 5.0.6 on 2026-06-22 00:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenedasset',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
