# Generated by Django 5.0.6 on 2026-06-16 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discoveryform',
            name='asset_code',
        ),
        migrations.RemoveField(
            model_name='discoveryform',
            name='asset_name',
        ),
        migrations.RemoveField(
            model_name='discoveryform',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='discoveryform',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='discoveryform',
            name='description',
        ),
        migrations.RemoveField(
            model_name='discoveryform',
            name='discovered_by',
        ),
        migrations.RemoveField(
            model_name='discoveryform',
            name='potential_value',
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='actions_immediate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='actions_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='actions_medium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='allocated_resources',
            field=models.TextField(blank=True, null=True, verbose_name='منابع اختصاص یافته'),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='approved_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='challenges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شرکت'),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='cultural_brand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='cultural_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='cultural_innovation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='cultural_values',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='discovery_methods_contracts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='discovery_methods_databases',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='discovery_methods_documentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='discovery_methods_instructions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='discovery_methods_interviews',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='discovery_methods_knowledge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='discovery_methods_processes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='discovery_methods_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='discovery_methods_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='discovery_methods_social',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='مدت زمان کشف'),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='economic_business_models',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='economic_copyrights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='economic_customer_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='economic_market_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='economic_patents',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='economic_trademarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='environmental_carbon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='environmental_green_tech',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='environmental_resource',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='environmental_sustainable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='knowledge_experiences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='knowledge_new_tech',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='knowledge_rd_results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='knowledge_technical',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='limitations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='operational_assets',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='prepared_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='prepared_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='project_goal',
            field=models.TextField(blank=True, null=True, verbose_name='هدف کشف'),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='project_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام پروژه کشف'),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='responsible_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مسئول تکمیل'),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='reviewed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='reviewed_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='search_scope',
            field=models.TextField(blank=True, null=True, verbose_name='محدوده جستجو'),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='social_business_networks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='social_charity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='social_csr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='social_stakeholders',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='strategic_assets',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='support_assets',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='discoveryform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discoveryform',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='واحد/بخش'),
        ),
    ]
