# Generated by Django 5.0.6 on 2026-06-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0002_alter_screenedasset_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenedasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
