# Generated by Django 5.0.6 on 2026-06-21 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0003_identityassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('manufacturing', 'تولیدی'), ('service', 'خدماتی'), ('rd', 'R&D'), ('holding', 'هلدینگ')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'نوع سازمان',
                'verbose_name_plural': 'انواع سازمان',
            },
        ),
        migrations.CreateModel(
            name='ScreeningTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='نام مورد غربالگری')),
                ('category', models.CharField(choices=[('strategic_economic', 'استراتژیک - اقتصادی'), ('strategic_social', 'استراتژیک - اجتماعی'), ('strategic_knowledge', 'استراتژیک - دانشی'), ('strategic_cultural', 'استراتژیک - فرهنگی'), ('strategic_environmental', 'استراتژیک - زیست\u200cمحیطی'), ('operational_economic', 'عملیاتی - اقتصادی'), ('operational_social', 'عملیاتی - اجتماعی'), ('operational_knowledge', 'عملیاتی - دانشی'), ('operational_cultural', 'عملیاتی - فرهنگی'), ('operational_environmental', 'عملیاتی - زیست\u200cمحیطی'), ('support_economic', 'پشتیبان - اقتصادی'), ('support_social', 'پشتیبان - اجتماعی'), ('support_knowledge', 'پشتیبان - دانشی'), ('support_cultural', 'پشتیبان - فرهنگی'), ('support_environmental', 'پشتیبان - زیست\u200cمحیطی')], max_length=50, verbose_name='دسته\u200cبندی')),
                ('default_result', models.CharField(choices=[('confirmed', 'دارایی قطعی'), ('conditional', 'مشروط'), ('rejected', 'رد شده')], default='confirmed', max_length=20, verbose_name='نتیجه پیش\u200cفرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('condition_1_non_physical', models.BooleanField(default=True, verbose_name='غیرفیزیکی بودن ✓')),
                ('condition_2_identifiable', models.BooleanField(default=True, verbose_name='شناسایی\u200cپذیری ✓')),
                ('condition_3_controllable', models.BooleanField(default=True, verbose_name='قابلیت کنترل ✓')),
                ('condition_4_value_creating', models.BooleanField(default=True, verbose_name='ارزش\u200cآفرینی ✓')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='intangible_assets.organizationtype')),
            ],
            options={
                'verbose_name': 'قالب غربالگری',
                'verbose_name_plural': 'قالب\u200cهای غربالگری',
                'ordering': ['organization_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ScreenedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_uid', models.CharField(max_length=50, unique=True, verbose_name='شناسه دارایی')),
                ('asset_name', models.CharField(max_length=255, verbose_name='نام دارایی')),
                ('category', models.CharField(max_length=50, verbose_name='دسته\u200cبندی')),
                ('result', models.CharField(choices=[('confirmed', 'دارایی قطعی'), ('conditional', 'مشروط'), ('rejected', 'رد شده')], default='confirmed', max_length=20, verbose_name='نتیجه غربالگری')),
                ('discovery_date', models.DateField(auto_now_add=True, verbose_name='تاریخ کشف')),
                ('last_update', models.DateField(auto_now=True, verbose_name='آخرین بازنگری')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='نسخه')),
                ('condition_1_non_physical', models.BooleanField(default=True, verbose_name='غیرفیزیکی بودن')),
                ('condition_2_identifiable', models.BooleanField(default=True, verbose_name='شناسایی\u200cپذیری')),
                ('condition_3_controllable', models.BooleanField(default=True, verbose_name='قابلیت کنترل')),
                ('condition_4_value_creating', models.BooleanField(default=True, verbose_name='ارزش\u200cآفرینی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discovery_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screened_assets', to='intangible_assets.discoveryform', verbose_name='فرم کشف مرتبط')),
                ('organization_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intangible_assets.organizationtype', verbose_name='نوع سازمان')),
                ('screening_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intangible_assets.screeningtemplate', verbose_name='قالب غربالگری')),
            ],
            options={
                'verbose_name': 'دارایی غربالگری شده',
                'verbose_name_plural': 'دارایی\u200cهای غربالگری شده',
                'ordering': ['-created_at'],
            },
        ),
    ]
