# Generated by Django 5.0.6 on 2026-06-24 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0004_assetfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ValuationDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('strategic', 'استراتژیک'), ('technical', 'فنی و بلوغ'), ('operational', 'عملیاتی'), ('market', 'بازار'), ('risk', 'ریسک')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, default=0.2, max_digits=3)),
                ('order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssetValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('in_progress', 'در حال ارزیابی'), ('completed', 'تکمیل شده'), ('verified', 'تأیید شده')], default='draft', max_length=20)),
                ('final_score', models.FloatField(default=0)),
                ('strategic_score', models.FloatField(default=0)),
                ('technical_score', models.FloatField(default=0)),
                ('operational_score', models.FloatField(default=0)),
                ('market_score', models.FloatField(default=0)),
                ('risk_score', models.FloatField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='intangible_assets.screenedasset')),
                ('asset_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intangible_assets.assettype')),
                ('evaluated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ValuationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('question_text', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('hint', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='intangible_assets.assettype')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='intangible_assets.valuationdimension')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('asset_type', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ValuationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵')], null=True)),
                ('evidence', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='intangible_assets.assetvaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intangible_assets.valuationquestion')),
            ],
            options={
                'unique_together': {('valuation', 'question')},
            },
        ),
        migrations.CreateModel(
            name='ValuationScoreGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, '۱'), (2, '۲'), (3, '۳'), (4, '۴'), (5, '۵')])),
                ('condition', models.TextField()),
                ('evidence_required', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_guides', to='intangible_assets.valuationquestion')),
            ],
            options={
                'ordering': ['score'],
                'unique_together': {('question', 'score')},
            },
        ),
    ]
