# Generated by Django 5.0.6 on 2026-06-27 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0005_assettype_valuationdimension_assetvaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenedasset',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screened_assets', to='intangible_assets.assettype'),
        ),
    ]
