# Generated by Django 5.0.6 on 2026-07-04 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0006_screenedasset_asset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_type', models.CharField(choices=[('manufacturing', 'تولیدی'), ('service', 'خدماتی'), ('rto', 'سازمان پژوهش و فناوری'), ('holding', 'هلدینگ یا مجموعه اقتصادی')], max_length=20)),
                ('strategic_weight', models.FloatField(default=0.25, verbose_name='وزن استراتژیک')),
                ('technical_weight', models.FloatField(default=0.2, verbose_name='وزن فنی و بلوغ')),
                ('operational_weight', models.FloatField(default=0.2, verbose_name='وزن عملیاتی')),
                ('market_weight', models.FloatField(default=0.25, verbose_name='وزن بازار')),
                ('risk_weight', models.FloatField(default=0.1, verbose_name='وزن ریسک')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='intangible_assets.assettype')),
            ],
            options={
                'verbose_name': 'وزن ارزیابی',
                'verbose_name_plural': 'وزن\u200cهای ارزیابی',
                'ordering': ['asset_type__code', 'organization_type'],
                'unique_together': {('asset_type', 'organization_type')},
            },
        ),
    ]
