# Generated by Django 5.0.6 on 2026-07-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0008_add_asset_type_to_screening_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningtemplate',
            name='asset_type',
        ),
    ]
