# Generated by Django 5.0.6 on 2026-07-06 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0009_add_asset_type_to_screening'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningtemplate',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screening_templates', to='intangible_assets.assettype'),
        ),
    ]
