# Generated by Django 5.0.6 on 2026-07-06 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0010_add_asset_type_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'اطلاعیه'), ('success', 'موفقیت'), ('warning', 'هشدار'), ('error', 'خطا'), ('urgent', 'فوری')], default='info', max_length=20)),
                ('category', models.CharField(choices=[('valuation', 'ارزیابی'), ('screening', 'غربالگری'), ('asset', 'دارایی'), ('system', 'سیستم')], default='system', max_length=20)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('link_text', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
