# Generated by Django 5.0.6 on 2026-07-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0011_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationanswer',
            name='evidence_database',
            field=models.FileField(blank=True, null=True, upload_to='evidence/databases/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='valuationanswer',
            name='evidence_document',
            field=models.FileField(blank=True, null=True, upload_to='evidence/documents/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='valuationanswer',
            name='evidence_interview',
            field=models.FileField(blank=True, null=True, upload_to='evidence/interviews/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='valuationanswer',
            name='evidence_process',
            field=models.FileField(blank=True, null=True, upload_to='evidence/processes/%Y/%m/%d/'),
        ),
    ]
