# Generated by Django 5.0.6 on 2026-07-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0013_add_valuation_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screeningtemplate',
            name='valuation_method',
        ),
    ]
