# Generated by Django 5.0.6 on 2026-07-08 14:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0015_screeningtemplate_valuation_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('strategic', 'استراتژیک'), ('operational', 'عملیاتی'), ('support', 'پشتیبان')], default='operational', max_length=20)),
                ('business_unit', models.CharField(max_length=255)),
                ('lifecycle_stage', models.CharField(blank=True, choices=[('birth', 'تولد'), ('growth', 'رشد'), ('maturity', 'بلوغ'), ('decline', 'افول'), ('re_innovation', 'نوآوری مجدد')], default='growth', max_length=20)),
                ('quality_override_reason', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('IRR', 'ریال'), ('USD', 'دلار'), ('EUR', 'یورو')], default='IRR', max_length=3)),
                ('inflation_basis', models.CharField(blank=True, choices=[('cost', 'هزینه'), ('market', 'بازار')], default='cost', max_length=10)),
                ('tax_rate', models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.5)])),
                ('discount_rate', models.FloatField(default=0.18, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(0.35)])),
                ('forecast_horizon', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)])),
                ('terminal_growth_rate', models.FloatField(default=0.05)),
                ('current_revenue', models.BigIntegerField(default=500000000000)),
                ('useful_life', models.IntegerField(blank=True, default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('source_reliability', models.CharField(choices=[('very_high', 'بسیار بالا'), ('high', 'بالا'), ('medium', 'متوسط'), ('low', 'پایین'), ('very_low', 'بسیار پایین')], default='high', max_length=20)),
                ('asset_description_doc', models.FileField(blank=True, null=True, upload_to='valuation/docs/%Y/%m/%d/')),
                ('ownership_doc', models.FileField(blank=True, null=True, upload_to='valuation/docs/%Y/%m/%d/')),
                ('financial_source_doc', models.FileField(blank=True, null=True, upload_to='valuation/docs/%Y/%m/%d/')),
                ('expert_input_doc', models.FileField(blank=True, null=True, upload_to='valuation/docs/%Y/%m/%d/')),
                ('external_benchmark_doc', models.FileField(blank=True, null=True, upload_to='valuation/docs/%Y/%m/%d/')),
                ('overlap_risk_level', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='medium', max_length=10)),
                ('overlap_type', models.CharField(choices=[('revenue', 'درآمد'), ('cost', 'هزینه'), ('knowledge', 'دانش'), ('market', 'بازار')], default='revenue', max_length=10)),
                ('review_status', models.CharField(choices=[('open', 'باز'), ('pending', 'در انتظار'), ('cleared', 'برطرف شده')], default='pending', max_length=10)),
                ('expert_note', models.TextField(blank=True, null=True)),
                ('valuation_method', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('in_progress', 'در حال ارزیابی'), ('completed', 'تکمیل شده'), ('verified', 'تأیید شده')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_score', models.FloatField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_cases', to='intangible_assets.screenedasset')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_cases', to=settings.AUTH_USER_MODEL)),
                ('linked_assets', models.ManyToManyField(blank=True, related_name='linked_valuations', to='intangible_assets.screenedasset')),
            ],
            options={
                'verbose_name': 'مورد ارزش\u200cگذاری',
                'verbose_name_plural': 'موارد ارزش\u200cگذاری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValuationAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumption_text', models.TextField()),
                ('assumption_tag', models.CharField(choices=[('general', 'عمومی'), ('asset_specific', 'مخصوص دارایی')], default='general', max_length=20)),
                ('assumption_critical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valuation_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='intangible_assets.valuationcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValuationEvidenceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.CharField(max_length=50)),
                ('tag', models.CharField(choices=[('asset_description', 'شرح دارایی'), ('ownership', 'مالکیت'), ('financial', 'مالی'), ('expert', 'نظر خبره'), ('benchmark', 'معیار خارجی')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valuation_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_tags', to='intangible_assets.valuationcase')),
            ],
            options={
                'unique_together': {('valuation_case', 'file_field')},
            },
        ),
    ]
