# Generated by Django 5.0.6 on 2026-07-08 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0016_add_valuation_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationStep3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_id', models.CharField(max_length=10)),
                ('method_inputs', models.JSONField(blank=True, default=dict)),
                ('validation_status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('VALIDATED', 'تأیید شده'), ('APPROVED', 'تصویب شده')], default='DRAFT', max_length=20)),
                ('validation_errors', models.IntegerField(default=0)),
                ('validation_warnings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valuation_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step3_data', to='intangible_assets.valuationcase')),
            ],
            options={
                'verbose_name': 'گام سوم ارزش\u200cگذاری',
                'verbose_name_plural': 'گام سوم ارزش\u200cگذاری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValuationStep3Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='valuation/step3/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('evidence_type', models.CharField(max_length=50)),
                ('method_id', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('step3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='intangible_assets.valuationstep3')),
            ],
        ),
    ]
