# Generated by Django 5.0.6 on 2026-07-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0017_add_valuation_step3_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenedasset',
            name='valuation_method',
            field=models.CharField(blank=True, help_text='روش ارزش\u200cگذاری انتخاب شده برای این دارایی', max_length=10, null=True),
        ),
    ]
