# Generated by Django 5.0.6 on 2026-07-08 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0018_screenedasset_valuation_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationStep4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_id', models.CharField(max_length=10)),
                ('final_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('confidence_level', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('qc_score', models.IntegerField(default=0)),
                ('calculation_details', models.JSONField(blank=True, default=dict)),
                ('step4_status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('CALCULATED', 'محاسبه شده'), ('APPROVED', 'تأیید شده')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valuation_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='step4_data', to='intangible_assets.valuationcase')),
            ],
            options={
                'verbose_name': 'گام چهارم ارزش\u200cگذاری',
                'verbose_name_plural': 'گام چهارم ارزش\u200cگذاری',
                'ordering': ['-created_at'],
            },
        ),
    ]
