# Generated by Django 5.0.6 on 2026-07-18 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0020_load_screening_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده')], default='pending', max_length=20)),
                ('n1', models.BooleanField(default=False)),
                ('n2', models.BooleanField(default=False)),
                ('n3', models.BooleanField(default=False)),
                ('n4', models.BooleanField(default=False)),
                ('n5', models.BooleanField(default=False)),
                ('n6', models.BooleanField(default=False)),
                ('n_score', models.IntegerField(default=0)),
                ('n_status', models.CharField(blank=True, max_length=20, null=True)),
                ('i1', models.BooleanField(default=False)),
                ('i2', models.BooleanField(default=False)),
                ('i3', models.BooleanField(default=False)),
                ('i4', models.BooleanField(default=False)),
                ('i5', models.BooleanField(default=False)),
                ('i6', models.BooleanField(default=False)),
                ('i7', models.BooleanField(default=False)),
                ('i_score', models.IntegerField(default=0)),
                ('i_status', models.CharField(blank=True, max_length=20, null=True)),
                ('c1', models.BooleanField(default=False)),
                ('c2', models.BooleanField(default=False)),
                ('c3', models.BooleanField(default=False)),
                ('c4', models.BooleanField(default=False)),
                ('c5', models.BooleanField(default=False)),
                ('c6', models.BooleanField(default=False)),
                ('c7', models.BooleanField(default=False)),
                ('c_score', models.IntegerField(default=0)),
                ('c_status', models.CharField(blank=True, max_length=20, null=True)),
                ('v1', models.BooleanField(default=False)),
                ('v2', models.BooleanField(default=False)),
                ('v3', models.BooleanField(default=False)),
                ('v4', models.BooleanField(default=False)),
                ('v5', models.BooleanField(default=False)),
                ('v6', models.BooleanField(default=False)),
                ('v7', models.BooleanField(default=False)),
                ('v8', models.BooleanField(default=False)),
                ('v9', models.BooleanField(default=False)),
                ('v_score', models.IntegerField(default=0)),
                ('v_status', models.CharField(blank=True, max_length=20, null=True)),
                ('final_status', models.CharField(blank=True, choices=[('CONFIRMED', 'قطعی'), ('CONDITIONAL', 'مشروط'), ('REJECTED', 'رد شده')], max_length=20, null=True)),
                ('recommendations', models.JSONField(blank=True, null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=29)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discovery', to='intangible_assets.screenedasset')),
            ],
            options={
                'verbose_name': 'ارزیابی شناسایی',
                'verbose_name_plural': 'ارزیابی\u200cهای شناسایی',
                'db_table': 'discovery_assessments',
            },
        ),
    ]
