# Generated by Django 5.0.6 on 2026-07-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0021_discoveryassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningtemplate',
            name='discovery_scores',
            field=models.JSONField(blank=True, null=True, verbose_name='نمرات موتور شناسایی'),
        ),
    ]
