# Generated by Django 5.0.6 on 2026-08-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0022_add_discovery_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationstep3evidence',
            name='cac_breakdown',
            field=models.FileField(blank=True, null=True, upload_to='valuation/cac/%Y/%m/%d/', verbose_name='فایل CAC Breakdown'),
        ),
        migrations.AddField(
            model_name='valuationstep3evidence',
            name='ebit_source',
            field=models.FileField(blank=True, null=True, upload_to='valuation/ebit/%Y/%m/%d/', verbose_name='فایل EBIT Source'),
        ),
    ]
