# Generated by Django 5.0.6 on 2026-08-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0023_valuationstep3evidence_cac_breakdown_and_more'),
    ]

    operations = [
    ]
