# Generated by Django 5.0.6 on 2026-08-03 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0024_add_sensitivity_model_manual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitivityAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_id', models.CharField(db_index=True, max_length=10)),
                ('base_value', models.DecimalField(decimal_places=2, max_digits=30)),
                ('tornado_data', models.JSONField(default=dict)),
                ('scenario_results', models.JSONField(default=dict)),
                ('critical_drivers', models.JSONField(default=list)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('std_deviation', models.FloatField(blank=True, null=True)),
                ('confidence_interval_low', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('confidence_interval_high', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('confidence_level', models.FloatField(default=0.95)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('calculated', 'محاسبه شده'), ('reviewed', 'بازبینی شده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensitivity_analyses', to=settings.AUTH_USER_MODEL)),
                ('step4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensitivity_analyses', to='intangible_assets.valuationstep4')),
                ('valuation_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitivity_analyses', to='intangible_assets.valuationcase')),
            ],
            options={
                'verbose_name': 'تحلیل حساسیت',
                'verbose_name_plural': 'تحلیل\u200cهای حساسیت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['valuation_case', 'method_id'], name='intangible__valuati_84af6e_idx'), models.Index(fields=['status'], name='intangible__status_4dd044_idx')],
                'unique_together': {('valuation_case', 'method_id')},
            },
        ),
    ]
