# Generated by Django 5.0.6 on 2026-08-06 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0025_add_sensitivity_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityControlResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_id', models.CharField(max_length=10)),
                ('completeness_score', models.IntegerField()),
                ('total_rules', models.IntegerField()),
                ('passed', models.IntegerField()),
                ('warnings', models.IntegerField()),
                ('errors', models.IntegerField()),
                ('blocking_issues', models.IntegerField()),
                ('decision', models.CharField(blank=True, choices=[('APPROVE', 'تأیید'), ('CONDITIONAL', 'مشروط'), ('RETURN', 'بازگشت')], max_length=20, null=True)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('qc_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valuation_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qc_result', to='intangible_assets.valuationcase')),
            ],
        ),
    ]
