# Generated by Django 5.0.6 on 2026-08-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0026_qualitycontrolresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationstep4',
            name='token_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
