# Generated by Django 5.0.6 on 2026-08-13 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0027_add_token_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetOntology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dimensions', to='intangible_assets.screenedasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EconomicDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valuation_method', models.CharField(blank=True, max_length=50)),
                ('revenue_stream', models.TextField(blank=True)),
                ('economic_impact', models.TextField(blank=True)),
                ('value_driver', models.CharField(blank=True, max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dimensions', to='intangible_assets.screenedasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EcosystemDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stakeholders', models.JSONField(blank=True, default=list)),
                ('partners', models.JSONField(blank=True, default=list)),
                ('markets', models.JSONField(blank=True, default=list)),
                ('ecosystem_impact', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dimensions', to='intangible_assets.screenedasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvolutionaryDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestones', models.JSONField(blank=True, default=list)),
                ('provenance_records', models.JSONField(blank=True, default=list)),
                ('version_history', models.JSONField(blank=True, default=list)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dimensions', to='intangible_assets.screenedasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patent_status', models.CharField(blank=True, max_length=50)),
                ('license_type', models.CharField(blank=True, max_length=50)),
                ('jurisdiction', models.CharField(blank=True, max_length=100)),
                ('nda_status', models.BooleanField(default=False)),
                ('protection_level', models.CharField(blank=True, max_length=50)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dimensions', to='intangible_assets.screenedasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationalDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(blank=True, max_length=255)),
                ('team', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('responsible_person', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dimensions', to='intangible_assets.screenedasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskOpportunityDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_indicators', models.JSONField(blank=True, default=list)),
                ('opportunities', models.JSONField(blank=True, default=list)),
                ('risk_score', models.FloatField(default=0)),
                ('opportunity_score', models.FloatField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dimensions', to='intangible_assets.screenedasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security_level', models.CharField(blank=True, max_length=50)),
                ('access_control_policy', models.TextField(blank=True)),
                ('data_classification', models.CharField(blank=True, max_length=50)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dimensions', to='intangible_assets.screenedasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrategicDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.CharField(blank=True, max_length=255)),
                ('strategic_priority', models.CharField(blank=True, max_length=100)),
                ('alignment_score', models.FloatField(default=0, help_text='امتیاز هم\u200cراستایی با استراتژی')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_dimensions', to='intangible_assets.screenedasset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
