# Generated by Django 5.0.6 on 2026-08-26 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0029_add_external_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سرویس')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_ips', models.JSONField(blank=True, default=list, verbose_name='IPهای مجاز')),
                ('rate_limit', models.IntegerField(default=100, verbose_name='محدودیت درخواست در دقیقه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'کلید API',
                'verbose_name_plural': 'کلیدهای API',
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='ExternalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source', models.CharField(max_length=100, verbose_name='منبع')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_users', to='intangible_assets.apikey')),
            ],
            options={
                'verbose_name': 'کاربر خارجی',
                'verbose_name_plural': 'کاربران خارجی',
                'db_table': 'external_users',
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=500, verbose_name='آدرس')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_status', models.IntegerField()),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('response_size', models.IntegerField(default=0, verbose_name='حجم پاسخ (بایت)')),
                ('status', models.CharField(choices=[('success', 'موفق'), ('failed', 'ناموفق'), ('error', 'خطا')], default='success', max_length=10)),
                ('response_time', models.FloatField(verbose_name='زمان پاسخ (میلی\u200cثانیه)')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intangible_assets.apikey')),
                ('internal_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('external_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intangible_assets.externaluser')),
            ],
            options={
                'verbose_name': 'لاگ درخواست',
                'verbose_name_plural': 'لاگ\u200cهای درخواست',
                'db_table': 'api_request_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
