# Generated by Django 5.0.6 on 2026-08-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0030_apikey_externaluser_apirequestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(max_length=500, verbose_name='نام سرویس'),
        ),
        migrations.AlterField(
            model_name='externaluser',
            name='session_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='externaluser',
            name='source',
            field=models.CharField(max_length=500, verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='screenedasset',
            name='asset_name',
            field=models.CharField(default='دارایی بدون نام', max_length=500),
        ),
        migrations.AlterField(
            model_name='screenedasset',
            name='session_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='شناسه جلسه'),
        ),
        migrations.AlterField(
            model_name='screenedasset',
            name='source_app',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='اپلیکیشن مبدا'),
        ),
    ]
