# Generated by Django 5.0.6 on 2026-08-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0031_alter_apikey_name_alter_externaluser_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaluser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
    ]
