# Generated by Django 5.0.6 on 2026-08-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0032_externaluser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationanswer',
            name='selected_option',
            field=models.TextField(blank=True, null=True, verbose_name='گزینه انتخاب شده'),
        ),
    ]
