# Generated by Django 5.0.6 on 2026-08-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0033_valuationanswer_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationanswer',
            name='question_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد سوال'),
        ),
    ]
