# Generated by Django 5.0.6 on 2026-09-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0034_valuationanswer_question_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningtemplate',
            name='protection_archetype',
            field=models.CharField(blank=True, choices=[('PA-1', 'مالکیت فکری ثبتی'), ('PA-2', 'قراردادی'), ('PA-3', 'راز تجاری'), ('PA-4', 'دیجیتال/داده'), ('PA-5', 'رویه\u200cای/فرهنگی'), ('N/A', 'قابل حفاظت نیست')], help_text='نوع استراتژی حفاظتی مناسب برای این دارایی بر اساس موتور ۳', max_length=5, null=True, verbose_name='آرکی\u200cتایپ حفاظتی'),
        ),
    ]
