# Generated by Django 5.0.6 on 2026-09-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0037_add_protection_tools'),
    ]

    operations = [
    ]
