# Generated by Django 5.0.6 on 2026-09-06 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0038_add_protection_tools'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='protectionprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='protectionstep1',
            options={},
        ),
        migrations.AlterModelOptions(
            name='protectionstep2',
            options={},
        ),
        migrations.AlterModelOptions(
            name='protectionstep3',
            options={},
        ),
        migrations.AlterModelOptions(
            name='protectionstep4',
            options={},
        ),
        migrations.AlterModelOptions(
            name='protectionstep5',
            options={},
        ),
    ]
