# Generated by Django 5.0.6 on 2026-09-08 12:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_external_fields_to_user'),
        ('intangible_assets', '0041_add_iam_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='screenedasset',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید'),
        ),
        migrations.AddField(
            model_name='screenedasset',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assets', to=settings.AUTH_USER_MODEL, verbose_name='تاییدکننده'),
        ),
        migrations.AddField(
            model_name='screenedasset',
            name='is_approved_for_valuation',
            field=models.BooleanField(default=False, verbose_name='تایید شده برای ارزش\u200cگذاری'),
        ),
        migrations.CreateModel(
            name='StrategicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان برنامه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('business_type', models.CharField(choices=[('manufacturing', 'تولیدی'), ('service', 'خدماتی'), ('rto', 'پژوهش و فناوری'), ('holding', 'هلدینگ اقتصادی')], default='manufacturing', max_length=20, verbose_name='نوع کسب\u200cوکار')),
                ('business_unit', models.CharField(blank=True, max_length=255, verbose_name='واحد کسب\u200cوکار')),
                ('start_year', models.IntegerField(verbose_name='سال شروع')),
                ('end_year', models.IntegerField(verbose_name='سال پایان')),
                ('policy_document', models.FileField(blank=True, null=True, upload_to='strategic_plans/policies/%Y/%m/%d/', verbose_name='سند خط مشی')),
                ('action_plan', models.FileField(blank=True, null=True, upload_to='strategic_plans/action_plans/%Y/%m/%d/', verbose_name='برنامه اجرایی')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('review', 'در حال بررسی'), ('approved', 'تصویب شده'), ('active', 'فعال'), ('archived', 'بایگانی شده')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تصویب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plans', to=settings.AUTH_USER_MODEL, verbose_name='تصویب\u200cکننده')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_plans', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'برنامه راهبردی',
                'verbose_name_plural': 'برنامه\u200cهای راهبردی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategicKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام KPI')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('discovery', 'کشف و شناسایی'), ('valuation', 'ارزش\u200cگذاری'), ('protection', 'حفاظت'), ('development', 'توسعه'), ('commercialization', 'تجاری\u200cسازی'), ('overall', 'کلی')], default='overall', max_length=20, verbose_name='دسته')),
                ('target_value', models.FloatField(verbose_name='مقدار هدف')),
                ('current_value', models.FloatField(default=0, verbose_name='مقدار فعلی')),
                ('unit', models.CharField(default='%', max_length=50, verbose_name='واحد')),
                ('responsible_unit', models.CharField(blank=True, max_length=255, verbose_name='واحد مسئول')),
                ('measurement_frequency', models.CharField(choices=[('daily', 'روزانه'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('quarterly', 'فصلی'), ('yearly', 'سالانه')], default='monthly', max_length=50, verbose_name='دوره اندازه\u200cگیری')),
                ('last_measurement', models.DateTimeField(blank=True, null=True, verbose_name='آخرین اندازه\u200cگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('strategic_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='intangible_assets.strategicplan')),
            ],
            options={
                'verbose_name': 'KPI راهبردی',
                'verbose_name_plural': 'KPIهای راهبردی',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_category', models.CharField(blank=True, max_length=100, verbose_name='دسته دارایی')),
                ('risk_description', models.TextField(verbose_name='توضیحات ریسک')),
                ('risk_category', models.CharField(choices=[('knowledge_loss', 'از دست دادن دانش'), ('ip_infringement', 'نقض مالکیت فکری'), ('data_breach', 'نشت داده'), ('contract_risk', 'ریسک قراردادی'), ('reputation', 'آسیب به اعتبار'), ('compliance', 'عدم انطباق'), ('operational', 'ریسک عملیاتی'), ('market', 'ریسک بازار')], default='operational', max_length=20, verbose_name='دسته ریسک')),
                ('impact_description', models.TextField(blank=True, verbose_name='توضیحات تأثیر')),
                ('likelihood', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='احتمال (۱-۵)')),
                ('impact', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='شدت تأثیر (۱-۵)')),
                ('risk_score', models.FloatField(default=0, verbose_name='امتیاز ریسک')),
                ('severity', models.CharField(choices=[('critical', 'بحرانی'), ('high', 'زیاد'), ('medium', 'متوسط'), ('low', 'کم')], default='medium', max_length=20, verbose_name='سطح ریسک')),
                ('mitigation_plan', models.TextField(blank=True, verbose_name='برنامه کاهش ریسک')),
                ('mitigation_status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال اجرا'), ('completed', 'انجام شده'), ('not_needed', 'نیاز نیست')], default='pending', max_length=20, verbose_name='وضعیت اقدام')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='تاریخ هدف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='intangible_assets.assettype')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_responsibilities', to=settings.AUTH_USER_MODEL, verbose_name='مسئول')),
                ('strategic_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='intangible_assets.strategicplan')),
            ],
            options={
                'verbose_name': 'ارزیابی ریسک',
                'verbose_name_plural': 'ارزیابی\u200cهای ریسک',
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='StrategicPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_category', models.CharField(blank=True, max_length=100, verbose_name='دسته دارایی')),
                ('asset_description', models.TextField(blank=True, verbose_name='توضیحات دارایی')),
                ('priority_level', models.CharField(choices=[('critical', 'بحرانی'), ('high', 'بالا'), ('medium', 'متوسط'), ('low', 'پایین')], default='medium', max_length=20, verbose_name='سطح اولویت')),
                ('focus_area', models.CharField(choices=[('investment', 'سرمایه\u200cگذاری'), ('protection', 'حفاظت'), ('development', 'توسعه'), ('commercialization', 'تجاری\u200cسازی'), ('monitoring', 'پایش')], default='protection', max_length=20, verbose_name='حوزه تمرکز')),
                ('justification', models.TextField(blank=True, verbose_name='توجیه')),
                ('expected_impact', models.TextField(blank=True, verbose_name='تأثیر مورد انتظار')),
                ('target_kpi', models.JSONField(blank=True, default=dict, verbose_name='KPI هدف')),
                ('responsible_unit', models.CharField(blank=True, max_length=255, verbose_name='واحد مسئول')),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='بودجه تخمینی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategic_priorities', to='intangible_assets.assettype')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategic_priorities', to=settings.AUTH_USER_MODEL, verbose_name='مسئول')),
                ('strategic_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='intangible_assets.strategicplan')),
            ],
            options={
                'verbose_name': 'اولویت استراتژیک',
                'verbose_name_plural': 'اولویت\u200cهای استراتژیک',
                'ordering': ['priority_level', '-created_at'],
            },
        ),
    ]
