# Generated by Django 5.0.6 on 2026-09-08 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0042_add_approval_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='screenedasset',
            name='is_approved_for_protection',
            field=models.BooleanField(default=False, verbose_name='تایید شده برای حفاظت'),
        ),
        migrations.AddField(
            model_name='screenedasset',
            name='protection_approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید حفاظت'),
        ),
        migrations.AddField(
            model_name='screenedasset',
            name='protection_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_protection_assets', to=settings.AUTH_USER_MODEL, verbose_name='تاییدکننده حفاظت'),
        ),
        migrations.AlterField(
            model_name='screeningtemplate',
            name='category',
            field=models.CharField(choices=[('strategic_economic', 'استراتژیک - اقتصادی'), ('strategic_social', 'استراتژیک - اجتماعی'), ('strategic_knowledge', 'استراتژیک - دانشی'), ('strategic_cultural', 'استراتژیک - فرهنگی'), ('strategic_environmental', 'استراتژیک - زیست\u200cمحیطی'), ('operational_economic', 'عملیاتی - اقتصادی'), ('operational_social', 'عملیاتی - اجتماعی'), ('operational_knowledge', 'عملیاتی - دانشی'), ('operational_cultural', 'عملیاتی - فرهنگی'), ('operational_environmental', 'عملیاتی - زیست\u200cمحیطی'), ('support_economic', 'پشتیبان -経済ی'), ('support_social', 'پشتیبان - اجتماعی'), ('support_knowledge', 'پشتیبان - دانشی'), ('support_cultural', 'پشتیبان - فرهنگی'), ('support_environmental', 'پشتیبان - زیست\u200cمحیطی')], max_length=50),
        ),
    ]
