from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('intangible_assets', '0044_viam_clean'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwarenessCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان کمپین')),
                ('campaign_type', models.CharField(choices=[('executive', 'حساس‌سازی مدیران ارشد'), ('middle', 'آگاه‌سازی مدیران میانی'), ('general', 'فرهنگ‌سازی عموم کارکنان')], max_length=20, verbose_name='نوع کمپین')),
                ('status', models.CharField(choices=[('draft', 'پیش‌نویس'), ('planned', 'برنامه‌ریزی شده'), ('active', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('key_messages', models.JSONField(default=list, verbose_name='پیام‌های کلیدی')),
                ('content_materials', models.JSONField(default=dict, verbose_name='محتوای تولیدی')),
                ('target_audience', models.JSONField(default=dict, verbose_name='مخاطبان هدف')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('kpis', models.JSONField(default=dict, verbose_name='KPIهای کمپین')),
                ('results', models.JSONField(blank=True, default=dict, verbose_name='نتایج')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viam_campaigns', to='accounts.user', verbose_name='ایجادکننده')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viam_campaigns', to='accounts.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'کمپین آگاه‌سازی',
                'verbose_name_plural': 'کمپین‌های آگاه‌سازی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveAwareness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_readiness', models.CharField(choices=[('unaware', 'بی‌اطلاع'), ('aware', 'آگاه'), ('committed', 'متعهد'), ('champion', 'حامی فعال')], default='unaware', max_length=20, verbose_name='آمادگی اولیه')),
                ('initial_notes', models.TextField(blank=True, verbose_name='یادداشت ارزیابی اولیه')),
                ('sessions_completed', models.IntegerField(default=0, verbose_name='تعداد جلسات برگزار شده')),
                ('last_session_date', models.DateTimeField(blank=True, null=True, verbose_name='آخرین جلسه')),
                ('executive_insight_report', models.FileField(blank=True, null=True, upload_to='viam/executive_reports/', verbose_name='گزارش بینش مدیران')),
                ('case_study_presented', models.TextField(blank=True, verbose_name='مطالعه موردی ارائه شده')),
                ('commitment_level', models.CharField(choices=[('unaware', 'بی‌اطلاع'), ('aware', 'آگاه'), ('committed', 'متعهد'), ('champion', 'حامی فعال')], default='unaware', max_length=20, verbose_name='سطح تعهد فعلی')),
                ('commitment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تعهد')),
                ('meeting_attendance_rate', models.FloatField(default=0, verbose_name='نرخ حضور در جلسات (%)')),
                ('approved_budget_percentage', models.FloatField(default=0, verbose_name='درصد بودجه مصوب (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_sessions', to='intangible_assets.awarenesscampaign', verbose_name='کمپین')),
                ('executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_awareness_sessions', to='accounts.user', verbose_name='مدیر ارشد')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_awareness', to='accounts.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'حساس‌سازی مدیر ارشد',
                'verbose_name_plural': 'حساس‌سازی مدیران ارشد',
                'unique_together': {('organization', 'executive')},
            },
        ),
        migrations.CreateModel(
            name='MiddleManagementAwareness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255, verbose_name='واحد سازمانی')),
                ('initial_skill_level', models.CharField(choices=[('novice', 'مبتدی'), ('aware', 'آگاه'), ('competent', 'توانمند'), ('expert', 'خبره')], default='novice', max_length=20, verbose_name='سطح مهارت اولیه')),
                ('knowledge_gap', models.JSONField(default=dict, verbose_name='شکاف دانشی')),
                ('training_status', models.CharField(choices=[('not_started', 'شروع نشده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('certified', 'گواهی دریافت کرده')], default='not_started', max_length=20, verbose_name='وضعیت آموزش')),
                ('training_completed_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل آموزش')),
                ('training_certificate', models.FileField(blank=True, null=True, upload_to='viam/training_certificates/', verbose_name='گواهی آموزش')),
                ('workshops_attended', models.IntegerField(default=0, verbose_name='تعداد کارگاه‌های شرکت کرده')),
                ('discovery_workshop_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ کارگاه کشف دارایی')),
                ('evidence_quality_score', models.FloatField(default=0, verbose_name='امتیاز کیفیت شواهد')),
                ('submission_response_time', models.FloatField(default=0, verbose_name='زمان پاسخ به درخواست تکمیل شواهد (ساعت)')),
                ('is_iam_representative', models.BooleanField(default=False, verbose_name='نماینده IAM واحد است؟')),
                ('representative_appointment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتصاب به عنوان نماینده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle_sessions', to='intangible_assets.awarenesscampaign', verbose_name='کمپین')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle_management_training', to='accounts.user', verbose_name='مدیر میانی')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle_awareness', to='accounts.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'آگاه‌سازی مدیر میانی',
                'verbose_name_plural': 'آگاه‌سازی مدیران میانی',
                'unique_together': {('organization', 'manager')},
            },
        ),
        migrations.CreateModel(
            name='GeneralEmployeeCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255, verbose_name='واحد سازمانی')),
                ('participation_level', models.CharField(choices=[('none', 'بدون مشارکت'), ('aware', 'آگاه'), ('active', 'فعال'), ('advocate', 'حامی')], default='none', max_length=20, verbose_name='سطح مشارکت')),
                ('campaign_messages_viewed', models.IntegerField(default=0, verbose_name='تعداد پیام‌های مشاهده شده')),
                ('campaign_materials_viewed', models.IntegerField(default=0, verbose_name='تعداد محتوای مشاهده شده')),
                ('suggestions_submitted', models.IntegerField(default=0, verbose_name='تعداد پیشنهادات ثبت شده')),
                ('suggestions_related_to_assets', models.IntegerField(default=0, verbose_name='پیشنهادات مرتبط با دارایی')),
                ('participated_in_campaigns', models.JSONField(default=list, verbose_name='کمپین‌های شرکت کرده')),
                ('knowledge_conversion_rate', models.FloatField(default=0, verbose_name='نرخ تبدیل دانش (%)')),
                ('documented_experiences', models.IntegerField(default=0, verbose_name='تعداد تجارب مستند شده')),
                ('culture_survey_score', models.FloatField(default=0, verbose_name='امتیاز نظرسنجی فرهنگ')),
                ('last_survey_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین نظرسنجی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_culture_sessions', to='intangible_assets.awarenesscampaign', verbose_name='کمپین')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='culture_participations', to='accounts.user', verbose_name='کارمند')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_culture', to='accounts.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'فرهنگ‌سازی کارمند',
                'verbose_name_plural': 'فرهنگ‌سازی کارمندان',
                'unique_together': {('organization', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='AwarenessContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('content_type', models.CharField(choices=[('video', 'ویدئو'), ('poster', 'پوستر'), ('infographic', 'اینفوگرافیک'), ('faq', 'پرسش و پاسخ'), ('case_study', 'مطالعه موردی'), ('presentation', 'ارائه'), ('article', 'مقاله'), ('newsletter', 'خبرنامه')], max_length=20, verbose_name='نوع محتوا')),
                ('audience', models.CharField(choices=[('executive', 'مدیران ارشد'), ('middle', 'مدیران میانی'), ('general', 'عموم کارکنان'), ('all', 'همه')], default='all', max_length=20, verbose_name='مخاطب هدف')),
                ('file', models.FileField(blank=True, null=True, upload_to='viam/contents/', verbose_name='فایل')),
                ('url', models.URLField(blank=True, null=True, verbose_name='لینک محتوا')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('key_message', models.TextField(verbose_name='پیام کلیدی')),
                ('tags', models.JSONField(default=list, verbose_name='برچسب‌ها')),
                ('view_count', models.IntegerField(default=0, verbose_name='تعداد بازدید')),
                ('like_count', models.IntegerField(default=0, verbose_name='تعداد لایک')),
                ('comment_count', models.IntegerField(default=0, verbose_name='تعداد نظرات')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='intangible_assets.awarenesscampaign', verbose_name='کمپین')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viam_contents', to='accounts.user', verbose_name='ایجادکننده')),
            ],
            options={
                'verbose_name': 'محتوای آگاه‌سازی',
                'verbose_name_plural': 'محتوای آگاه‌سازی',
                'ordering': ['-created_at'],
            },
        ),
    ]
