# Generated by Django 5.0.6 on 2026-09-08 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_external_fields_to_user'),
        ('intangible_assets', '0047_viam_04_clean'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='iammeetingattendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='iammeetingattendance',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='iammeetingattendance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='iamuserprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='iamuserprofile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='iamuserprofile',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='iamuserprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='strategic_plan',
        ),
        migrations.RemoveField(
            model_name='strategickpi',
            name='strategic_plan',
        ),
        migrations.RemoveField(
            model_name='strategicpriority',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='strategicpriority',
            name='responsible_person',
        ),
        migrations.RemoveField(
            model_name='strategicpriority',
            name='strategic_plan',
        ),
        migrations.AlterModelOptions(
            name='establishmentrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='iamcharter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='iamcommittee',
            options={'verbose_name': 'کمیته IAM', 'verbose_name_plural': 'کمیته\u200cهای IAM'},
        ),
        migrations.AlterModelOptions(
            name='iamcommitteemeeting',
            options={'ordering': ['-scheduled_date'], 'verbose_name': 'جلسه کمیته', 'verbose_name_plural': 'جلسات کمیته'},
        ),
        migrations.AlterModelOptions(
            name='iampolicy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='iamrepresentative',
            options={},
        ),
        migrations.AlterModelOptions(
            name='iamresolution',
            options={'ordering': ['-created_at'], 'verbose_name': 'مصوبه کمیته', 'verbose_name_plural': 'مصوبات کمیته'},
        ),
        migrations.AlterModelOptions(
            name='operationalmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='racimatrix',
            options={},
        ),
        migrations.AlterModelOptions(
            name='strategicassetmapping',
            options={},
        ),
        migrations.AlterModelOptions(
            name='strategicinitiative',
            options={},
        ),
        migrations.AlterModelOptions(
            name='strategicplan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='viampilot',
            options={},
        ),
        migrations.RemoveField(
            model_name='iamcommittee',
            name='chairperson',
        ),
        migrations.RemoveField(
            model_name='iamcommittee',
            name='description',
        ),
        migrations.RemoveField(
            model_name='iamcommittee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='iamcommitteemeeting',
            name='date',
        ),
        migrations.RemoveField(
            model_name='iamcommitteemeeting',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='iamresolution',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='iamresolution',
            name='decision_type',
        ),
        migrations.RemoveField(
            model_name='iamresolution',
            name='evidence',
        ),
        migrations.AddField(
            model_name='iamcommittee',
            name='chair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_committees', to=settings.AUTH_USER_MODEL, verbose_name='رئیس کمیته'),
        ),
        migrations.AddField(
            model_name='iamcommittee',
            name='charter_file',
            field=models.FileField(blank=True, null=True, upload_to='viam/committee/charters/', verbose_name='اساسنامه کمیته'),
        ),
        migrations.AddField(
            model_name='iamcommittee',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_committees', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iamcommittee',
            name='dissolved_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انحلال'),
        ),
        migrations.AddField(
            model_name='iamcommittee',
            name='formation_file',
            field=models.FileField(blank=True, null=True, upload_to='viam/committee/formation/', verbose_name='مدارک تشکیل کمیته'),
        ),
        migrations.AddField(
            model_name='iamcommittee',
            name='formed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تشکیل'),
        ),
        migrations.AddField(
            model_name='iamcommittee',
            name='meeting_days',
            field=models.JSONField(default=list, help_text='لیست روزهای هفته برای جلسات', verbose_name='روزهای جلسات'),
        ),
        migrations.AddField(
            model_name='iamcommittee',
            name='meeting_frequency',
            field=models.CharField(default='ماهانه', max_length=50, verbose_name='دوره تشکیل جلسات'),
        ),
        migrations.AddField(
            model_name='iamcommittee',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True, verbose_name='زمان جلسات'),
        ),
        migrations.AddField(
            model_name='iamcommittee',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='iam_committees', to='accounts.organization', verbose_name='سازمان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iamcommittee',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('dissolved', 'منحل شده')], default='active', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='iamcommitteemeeting',
            name='absentees',
            field=models.ManyToManyField(blank=True, related_name='meeting_absences', to=settings.AUTH_USER_MODEL, verbose_name='غایبان'),
        ),
        migrations.AddField(
            model_name='iamcommitteemeeting',
            name='action_items',
            field=models.JSONField(default=list, help_text='لیست اقدامات با مسئول و زمان', verbose_name='اقدامات'),
        ),
        migrations.AddField(
            model_name='iamcommitteemeeting',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iamcommitteemeeting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان'),
        ),
        migrations.AddField(
            model_name='iamcommitteemeeting',
            name='meeting_number',
            field=models.CharField(default=1, max_length=20, verbose_name='شماره جلسه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iamcommitteemeeting',
            name='minutes_file',
            field=models.FileField(blank=True, null=True, upload_to='viam/committee/minutes/', verbose_name='فایل صورتجلسه'),
        ),
        migrations.AddField(
            model_name='iamcommitteemeeting',
            name='scheduled_date',
            field=models.DateTimeField(default=1, verbose_name='تاریخ و زمان برنامه\u200cریزی شده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iamcommitteemeeting',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع'),
        ),
        migrations.AddField(
            model_name='iamresolution',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='مبلغ بودجه'),
        ),
        migrations.AddField(
            model_name='iamresolution',
            name='budget_approved',
            field=models.BooleanField(default=False, verbose_name='بودجه تصویب شده؟'),
        ),
        migrations.AddField(
            model_name='iamresolution',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تکمیل'),
        ),
        migrations.AddField(
            model_name='iamresolution',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_resolutions', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iamresolution',
            name='details',
            field=models.JSONField(default=dict, help_text='جزئیات کامل مصوبه', verbose_name='جزئیات'),
        ),
        migrations.AddField(
            model_name='iamresolution',
            name='progress_notes',
            field=models.TextField(blank=True, verbose_name='یادداشت پیشرفت'),
        ),
        migrations.AddField(
            model_name='iamresolution',
            name='progress_percentage',
            field=models.IntegerField(default=0, verbose_name='درصد پیشرفت'),
        ),
        migrations.AddField(
            model_name='iamresolution',
            name='resolution_type',
            field=models.CharField(choices=[('asset_registration', 'تأیید ثبت دارایی'), ('ownership', 'تعیین مالکیت'), ('legal_protection', 'تصویب حفاظت حقوقی'), ('valuation', 'تصویب ارزش\u200cگذاری'), ('development', 'تأیید پروژه توسعه'), ('commercialization', 'تأیید تجاری\u200cسازی'), ('budget', 'تصویب بودجه'), ('compliance', 'ارجاع عدم انطباق'), ('other', 'سایر')], default=1, max_length=30, verbose_name='نوع مصوبه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='establishmentrequest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='establishmentrequest',
            name='justification',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='establishmentrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ارسال شده'), ('approved', 'تأیید شده'), ('rejected', 'رد شده')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='establishmentrequest',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='iamcharter',
            name='governance_structure',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='iamcharter',
            name='meeting_frequency',
            field=models.CharField(default='ماهانه', max_length=50),
        ),
        migrations.AlterField(
            model_name='iamcharter',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='iamcharter',
            name='objectives',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='iamcharter',
            name='scope',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='iamcharter',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('approved', 'تأیید شده'), ('active', 'فعال')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='iamcharter',
            name='title',
            field=models.CharField(default='منشور IAM', max_length=255),
        ),
        migrations.AlterField(
            model_name='iamcharter',
            name='values',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='iamcharter',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='iamcharter',
            name='vision',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='iamcommittee',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='committee_memberships', to=settings.AUTH_USER_MODEL, verbose_name='اعضای کمیته'),
        ),
        migrations.AlterField(
            model_name='iamcommittee',
            name='name',
            field=models.CharField(default='کمیته IAM', max_length=255, verbose_name='نام کمیته'),
        ),
        migrations.AlterField(
            model_name='iamcommittee',
            name='secretary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_committees', to=settings.AUTH_USER_MODEL, verbose_name='دبیر کمیته'),
        ),
        migrations.AlterField(
            model_name='iamcommitteemeeting',
            name='agenda',
            field=models.JSONField(default=list, help_text='لیست موارد دستور جلسه', verbose_name='دستور جلسه'),
        ),
        migrations.AlterField(
            model_name='iamcommitteemeeting',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL, verbose_name='حاضران'),
        ),
        migrations.AlterField(
            model_name='iamcommitteemeeting',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='intangible_assets.iamcommittee', verbose_name='کمیته'),
        ),
        migrations.AlterField(
            model_name='iamcommitteemeeting',
            name='resolutions',
            field=models.JSONField(default=list, help_text='لیست مصوبات جلسه', verbose_name='مصوبات'),
        ),
        migrations.AlterField(
            model_name='iamcommitteemeeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'برنامه\u200cریزی شده'), ('in_progress', 'در حال برگزاری'), ('completed', 'برگزار شده'), ('cancelled', 'لغو شده')], default='scheduled', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='iampolicy',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='iampolicy',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iampolicy',
            name='policy_type',
            field=models.CharField(choices=[('general', 'عمومی'), ('discovery', 'کشف'), ('protection', 'حفاظت')], max_length=20),
        ),
        migrations.AlterField(
            model_name='iampolicy',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('approved', 'تأیید'), ('active', 'فعال')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='iampolicy',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='iamrepresentative',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='iamrepresentative',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='iamrepresentative',
            name='role',
            field=models.CharField(choices=[('unit_manager', 'مدیر واحد'), ('deputy', 'معاون'), ('expert', 'کارشناس')], default='unit_manager', max_length=20),
        ),
        migrations.AlterField(
            model_name='iamresolution',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='iamresolution',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions_list', to='intangible_assets.iamcommitteemeeting', verbose_name='جلسه'),
        ),
        migrations.AlterField(
            model_name='iamresolution',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_resolutions', to=settings.AUTH_USER_MODEL, verbose_name='مسئول اجرا'),
        ),
        migrations.AlterField(
            model_name='iamresolution',
            name='status',
            field=models.CharField(choices=[('proposed', 'پیشنهادی'), ('approved', 'مصوب'), ('rejected', 'رد شده'), ('in_progress', 'در حال اجرا'), ('completed', 'اجرا شده'), ('blocked', 'مسدود')], default='proposed', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='operationalmodel',
            name='kpis',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='operationalmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='operationalmodel',
            name='processes',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='operationalmodel',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('approved', 'تأیید شده'), ('active', 'فعال')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='operationalmodel',
            name='workflows',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='racimatrix',
            name='activity',
            field=models.CharField(choices=[('discovery', 'کشف'), ('valuation', 'ارزش\u200cگذاری'), ('protection', 'حفاظت'), ('development', 'توسعه')], max_length=20),
        ),
        migrations.AlterField(
            model_name='racimatrix',
            name='responsibility',
            field=models.CharField(choices=[('R', 'مسئول'), ('A', 'پاسخگو'), ('C', 'مشورت'), ('I', 'مطلع')], max_length=1),
        ),
        migrations.AlterField(
            model_name='racimatrix',
            name='role',
            field=models.CharField(choices=[('org_admin', 'مدیر شرکت'), ('unit_manager', 'مدیر واحد'), ('legal', 'حقوقی'), ('it', 'فناوری')], max_length=20),
        ),
        migrations.AlterField(
            model_name='strategicassetmapping',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='strategicassetmapping',
            name='strategic_importance',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='strategicinitiative',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='strategicinitiative',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategicinitiative',
            name='priority',
            field=models.CharField(choices=[('high', 'بالا'), ('medium', 'متوسط'), ('low', 'پایین')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategicinitiative',
            name='progress_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='strategicinitiative',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategicinitiative',
            name='status',
            field=models.CharField(choices=[('planned', 'برنامه'), ('in_progress', 'در حال اجرا'), ('completed', 'تکمیل')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategicinitiative',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('approved', 'تأیید'), ('active', 'فعال')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='strategic_goals',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='strategicplan',
            name='vision',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='viampilot',
            name='asset_count_target',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='viampilot',
            name='assets_discovered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viampilot',
            name='assets_registered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viampilot',
            name='departments',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='viampilot',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viampilot',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='viampilot',
            name='scope',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='viampilot',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viampilot',
            name='status',
            field=models.CharField(choices=[('planned', 'برنامه\u200cریزی'), ('in_progress', 'در حال اجرا'), ('completed', 'تکمیل شده')], default='planned', max_length=20),
        ),
        migrations.CreateModel(
            name='IAMDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_type', models.CharField(choices=[('approve', 'تصویب'), ('reject', 'رد'), ('defer', 'تعویق'), ('refer', 'ارجاع')], max_length=20, verbose_name='نوع تصمیم')),
                ('decision_text', models.TextField(verbose_name='متن تصمیم')),
                ('voting_method', models.CharField(default='توافقی', max_length=50, verbose_name='روش رأی\u200cگیری')),
                ('votes_for', models.IntegerField(default=0, verbose_name='موافق')),
                ('votes_against', models.IntegerField(default=0, verbose_name='مخالف')),
                ('votes_abstain', models.IntegerField(default=0, verbose_name='ممتنع')),
                ('decision_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ تصمیم')),
                ('execution_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ اجرا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_decisions', to=settings.AUTH_USER_MODEL, verbose_name='مجری')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='intangible_assets.iamcommitteemeeting', verbose_name='جلسه')),
                ('resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='intangible_assets.iamresolution', verbose_name='مصوبه')),
            ],
            options={
                'verbose_name': 'لاگ تصمیم',
                'verbose_name_plural': 'لاگ تصمیمات',
                'ordering': ['-decision_date'],
            },
        ),
        migrations.DeleteModel(
            name='IAMCommitteeMembership',
        ),
        migrations.DeleteModel(
            name='IAMMeetingAttendance',
        ),
        migrations.DeleteModel(
            name='IAMRole',
        ),
        migrations.DeleteModel(
            name='IAMUserProfile',
        ),
        migrations.DeleteModel(
            name='RiskAssessment',
        ),
        migrations.DeleteModel(
            name='StrategicKPI',
        ),
        migrations.DeleteModel(
            name='StrategicPriority',
        ),
    ]
