# Generated by Django 5.0.6 on 2026-09-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0048_viam_07_done'),
    ]

    operations = [
        # ستون valuation_type به صورت دستی در DB اضافه شده است
        # این migration فقط state جنگو را هماهنگ می‌کند
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='screenedasset',
                    name='valuation_type',
                    field=models.CharField(
                        blank=True,
                        choices=[
                            ('DCF', 'DCF - Discounted Cash Flow (جریان نقدی تنزیل شده)'),
                            ('NAV', 'NAV - Net Asset Value (ارزش خالص دارایی)'),
                        ],
                        help_text='نوع ارزش‌گذاری انتخاب شده توسط کاربر (DCF یا NAV)',
                        max_length=10,
                        null=True,
                        verbose_name='نوع ارزش‌گذاری',
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
