# Generated by Django 5.0.6 on 2026-09-15 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_external_fields_to_user'),
        ('intangible_assets', '0051_businesstype_establishmentrequest_current_step_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RACITemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('manufacturing', 'تولیدی'), ('service', 'خدماتی'), ('rto', 'پژوهش و فناوری'), ('holding', 'هلدینگ اقتصادی')], default='manufacturing', max_length=20, verbose_name='نوع کسبوکار')),
                ('matrix', models.JSONField(default=dict, help_text='ماتریس ۲۰ فعالیت × ۱۴ نقش', verbose_name='ماتریس RACI')),
                ('role_assignments', models.JSONField(default=dict, help_text='نقشها به کاربران', verbose_name='تخصیص کاربران به نقشها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='raci_template', to='accounts.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'RACI استاندارد سازمان',
                'verbose_name_plural': 'RACIهای استاندارد سازمان',
            },
        ),
    ]
