# Generated by Django 5.0.6 on 2026-09-15 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_external_fields_to_user'),
        ('intangible_assets', '0052_racitemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(help_text='مثال: شرکت فولاد - IAM', max_length=255, verbose_name='نام Tenant')),
                ('enabled_modules', models.JSONField(default=list, help_text='لیست کدهای VIAM که فعال هستند', verbose_name='ماژول\u200cهای فعال')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای پیکربندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='پنل IAM فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_configs', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_config', to='accounts.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'پیکربندی Tenant',
                'verbose_name_plural': 'پیکربندی\u200cهای Tenant',
            },
        ),
    ]
