# Generated by Django 5.0.6 on 2026-09-15 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_department_options_alter_organization_options_and_more'),
        ('intangible_assets', '0053_tenantconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenedasset',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screened_assets', to='accounts.department', verbose_name='واحد'),
        ),
        migrations.AddField(
            model_name='screenedasset',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screened_assets', to='accounts.organization', verbose_name='سازمان'),
        ),
    ]
