# Generated by Django 5.0.6 on 2026-09-16 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_department_options_alter_organization_options_and_more'),
        ('intangible_assets', '0054_screenedasset_department_screenedasset_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان ایده')),
                ('concept_desc', models.TextField(verbose_name='شرح مفهوم')),
                ('source', models.CharField(choices=[('rnd', 'R&D داخلی'), ('employee', 'پیشنهاد کارکنان'), ('external', 'شریک خارجی'), ('university', 'دانشگاه'), ('market', 'بازار'), ('other', 'سایر')], default='rnd', max_length=20, verbose_name='منبع')),
                ('tech_domain', models.CharField(choices=[('software', 'نرم\u200cافزار'), ('hardware', 'سخت\u200cافزار'), ('chemical', 'شیمیایی'), ('mechanical', 'مکانیکی'), ('biotech', 'بیوتکنولوژی'), ('process', 'فرآیند'), ('business_model', 'مدل کسب\u200cوکار'), ('other', 'سایر')], default='other', max_length=30, verbose_name='حوزه فناوری')),
                ('strategic_alignment', models.FloatField(default=0, verbose_name='همسویی استراتژیک (۰-۵)')),
                ('target_module', models.CharField(default='INNO', editable=False, max_length=10, verbose_name='ماژول مقصد')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('submitted', 'ارسال شده'), ('scored', 'امتیازدهی شده'), ('approved', 'تأیید شده'), ('backlog', 'در انتظار'), ('rejected', 'رد شده'), ('in_progress', 'در حال اجرا'), ('completed', 'تکمیل شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_innovation_ideas', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='innovation_ideas', to='accounts.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'ایده نوآوری',
                'verbose_name_plural': 'ایده\u200cهای نوآوری',
                'ordering': ['-strategic_alignment', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=500, verbose_name='نام دارایی')),
                ('gap_type', models.CharField(choices=[('strategic', 'شکاف استراتژیک'), ('technical', 'شکاف فنی'), ('operational', 'شکاف عملیاتی'), ('market', 'شکاف بازار'), ('risk', 'شکاف ریسک'), ('mixed', 'شکاف ترکیبی')], default='mixed', max_length=20, verbose_name='نوع شکاف')),
                ('current_s', models.FloatField(default=0, verbose_name='امتیاز فعلی استراتژیک')),
                ('current_t', models.FloatField(default=0, verbose_name='امتیاز فعلی فنی')),
                ('current_o', models.FloatField(default=0, verbose_name='امتیاز فعلی عملیاتی')),
                ('current_m', models.FloatField(default=0, verbose_name='امتیاز فعلی بازار')),
                ('current_r', models.FloatField(default=0, verbose_name='امتیاز فعلی ریسک')),
                ('target_s', models.FloatField(default=4.5, verbose_name='هدف استراتژیک')),
                ('target_t', models.FloatField(default=4.5, verbose_name='هدف فنی')),
                ('target_o', models.FloatField(default=4.5, verbose_name='هدف عملیاتی')),
                ('target_m', models.FloatField(default=4.5, verbose_name='هدف بازار')),
                ('target_r', models.FloatField(default=4.5, verbose_name='هدف ریسک')),
                ('gap_score', models.FloatField(default=0, verbose_name='امتیاز شکاف کل')),
                ('is_critical', models.BooleanField(default=False, verbose_name='شکاف بحرانی')),
                ('potential_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='ارزش بالقوه (ریال)')),
                ('target_module', models.CharField(choices=[('DEV', 'توسعه دارایی موجود'), ('INNO', 'خلق دارایی جدید')], default='DEV', max_length=10, verbose_name='ماژول مقصد')),
                ('status', models.CharField(choices=[('identified', 'شناسایی شده'), ('scored', 'امتیازدهی شده'), ('approved', 'تأیید شده'), ('backlog', 'در انتظار'), ('rejected', 'رد شده'), ('in_progress', 'در حال اجرا'), ('completed', 'تکمیل شده')], default='identified', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('recommendation', models.TextField(blank=True, verbose_name='توصیه اقدام')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='development_opportunities', to='intangible_assets.screenedasset', verbose_name='دارایی مرجع')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='development_opportunities', to='accounts.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'فرصت توسعه',
                'verbose_name_plural': 'فرصت\u200cهای توسعه',
                'ordering': ['-gap_score', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='intangible__organiz_1e2945_idx'), models.Index(fields=['target_module', 'status'], name='intangible__target__d2bba4_idx'), models.Index(fields=['is_critical'], name='intangible__is_crit_bc9249_idx')],
            },
        ),
    ]
