# Generated by Django 5.0.6 on 2026-09-16 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_department_options_alter_organization_options_and_more'),
        ('intangible_assets', '0055_innovationidea_developmentopportunity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrioritizedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='عنوان پروژه')),
                ('project_type', models.CharField(choices=[('DEV', 'توسعه دارایی'), ('INNO', 'خلق دارایی جدید')], max_length=10, verbose_name='نوع پروژه')),
                ('c1_strategic', models.FloatField(default=0, verbose_name='ارزش استراتژیک (C1)')),
                ('c2_roi', models.FloatField(default=0, verbose_name='بازگشت سرمایه (C2)')),
                ('c3_feasibility', models.FloatField(default=0, verbose_name='امکان\u200cپذیری (C3)')),
                ('c4_goal_alignment', models.FloatField(default=0, verbose_name='هم\u200cراستایی اهداف (C4)')),
                ('c5_urgency', models.FloatField(default=0, verbose_name='فوریت (C5)')),
                ('priority_score', models.FloatField(default=0, verbose_name='امتیاز اولویت')),
                ('rank', models.IntegerField(default=0, verbose_name='رتبه')),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='بودجه تخمینی (ریال)')),
                ('approved_budget', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='بودجه مصوب (ریال)')),
                ('approval_status', models.CharField(choices=[('pending', 'در انتظار تصمیم'), ('approved', 'تأیید شده'), ('backlog', 'در انتظار'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت تصویب')),
                ('committee_comment', models.TextField(blank=True, verbose_name='نظر کمیته')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_projects', to=settings.AUTH_USER_MODEL, verbose_name='تأییدکننده')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('innovation_idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prioritized_projects', to='intangible_assets.innovationidea', verbose_name='ایده نوآوری')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prioritized_projects', to='intangible_assets.developmentopportunity', verbose_name='فرصت توسعه')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prioritized_projects', to='accounts.organization', verbose_name='سازمان')),
            ],
            options={
                'verbose_name': 'پروژه اولویت\u200cبندی\u200cشده',
                'verbose_name_plural': 'پروژه\u200cهای اولویت\u200cبندی\u200cشده',
                'ordering': ['rank', '-priority_score'],
            },
        ),
        migrations.CreateModel(
            name='GanttSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('milestones', models.JSONField(default=list, help_text='لیست: [{id, name, due_date, gate_decision_required, status}]', verbose_name='Milestoneها')),
                ('wbs', models.JSONField(default=list, help_text='لیست: [{id, name, parent, duration, owner, status}]', verbose_name='WBS')),
                ('physical_progress', models.FloatField(default=0, verbose_name='پیشرفت فیزیکی (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gantt_schedule', to='intangible_assets.prioritizedproject', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'زمان\u200cبندی گانت',
                'verbose_name_plural': 'زمان\u200cبندی\u200cهای گانت',
            },
        ),
        migrations.CreateModel(
            name='DevelopedOrNewAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new', models.BooleanField(default=False, verbose_name='دارایی جدید؟')),
                ('tech_docs_url', models.URLField(blank=True, verbose_name='لینک مستندات فنی')),
                ('source_code_or_design', models.TextField(blank=True, verbose_name='سورس\u200cکد یا طراحی')),
                ('version', models.CharField(default='1.0.0', max_length=50, verbose_name='نسخه')),
                ('attachments', models.JSONField(default=list, help_text='لیست: [{name, url, type}]', verbose_name='فایل\u200cهای پیوست')),
                ('registered_in_engine_1', models.BooleanField(default=False, verbose_name='ثبت در موتور ۱')),
                ('protected_in_engine_3', models.BooleanField(default=False, verbose_name='حفاظت در موتور ۳')),
                ('valued_in_engine_2', models.BooleanField(default=False, verbose_name='ارزش\u200cگذاری در موتور ۲')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_developed_assets', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('new_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_projects', to='intangible_assets.screenedasset', verbose_name='دارایی جدید')),
                ('source_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developed_versions', to='intangible_assets.screenedasset', verbose_name='دارایی مرجع')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developed_assets', to='intangible_assets.prioritizedproject', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'دارایی توسعه\u200cیافته/جدید',
                'verbose_name_plural': 'دارایی\u200cهای توسعه\u200cیافته/جدید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocatedBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capex', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='هزینه سرمایه\u200cای (Capex) - ریال')),
                ('opex', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='هزینه عملیاتی (Opex) - ریال')),
                ('contingency_reserve', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='ذخیره احتمالی - ریال')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='جمع کل - ریال')),
                ('consumed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='مصرف\u200cشده - ریال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_budget', to='intangible_assets.prioritizedproject', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'بودجه تخصیص\u200cیافته',
                'verbose_name_plural': 'بودجه\u200cهای تخصیص\u200cیافته',
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.IntegerField(default=1, verbose_name='شماره گزارش')),
                ('report_date', models.DateField(auto_now_add=True, verbose_name='تاریخ گزارش')),
                ('physical_progress_pct', models.FloatField(default=0, verbose_name='پیشرفت فیزیکی (%)')),
                ('budget_consumed_pct', models.FloatField(default=0, verbose_name='مصرف بودجه (%)')),
                ('spi', models.FloatField(default=1.0, verbose_name='SPI (شاخص عملکرد زمانی)')),
                ('cpi', models.FloatField(default=1.0, verbose_name='CPI (شاخص عملکرد هزینه)')),
                ('active_risks', models.JSONField(default=list, help_text='لیست: [{risk, impact, status}]', verbose_name='ریسک\u200cهای فعال')),
                ('gate_decision', models.CharField(choices=[('go', 'ادامه به فاز بعد'), ('recycle', 'اصلاح فاز فعلی'), ('hold', 'تعلیق موقت'), ('kill', 'توقف و ابطال'), ('na', 'بدون تصمیم')], default='na', max_length=20, verbose_name='تصمیم گیت')),
                ('gate_notes', models.TextField(blank=True, verbose_name='یادداشت تصمیم گیت')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='intangible_assets.prioritizedproject', verbose_name='پروژه')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_progress', to=settings.AUTH_USER_MODEL, verbose_name='گزارش\u200cدهنده')),
            ],
            options={
                'verbose_name': 'گزارش پیشرفت',
                'verbose_name_plural': 'گزارش\u200cهای پیشرفت',
                'ordering': ['-report_date', '-report_number'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.TextField(verbose_name='محدوده پروژه')),
                ('business_case', models.TextField(blank=True, verbose_name='توجیه کسب\u200cوکار')),
                ('target_kpis', models.JSONField(default=list, help_text='لیست: [{name, target, unit}]', verbose_name='KPIهای هدف')),
                ('methodology', models.CharField(choices=[('linear', 'آبشاری / خطی'), ('stage_gate', 'مرحله\u200cای (Stage-Gate)')], default='linear', max_length=20, verbose_name='متدولوژی')),
                ('team_assigned', models.JSONField(default=list, help_text='لیست: [{user_id, role, name}]', verbose_name='تیم تخصیص\u200cیافته')),
                ('risks', models.JSONField(default=list, help_text='لیست: [{risk, impact, mitigation}]', verbose_name='ریسک\u200cها')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('approved', 'تأیید شده'), ('active', 'فعال'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_charters', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charter', to='intangible_assets.prioritizedproject', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'منشور پروژه',
                'verbose_name_plural': 'منشورهای پروژه',
            },
        ),
        migrations.CreateModel(
            name='ProjectClosureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_kpi_score', models.FloatField(default=0, verbose_name='امتیاز نهایی KPI')),
                ('variance_summary', models.JSONField(default=dict, help_text='{schedule_variance, cost_variance, scope_variance}', verbose_name='خلاصه انحرافات')),
                ('lessons_learned', models.TextField(blank=True, verbose_name='درس\u200cآموخته\u200cها')),
                ('realized_roi', models.FloatField(default=0, verbose_name='ROI محقق\u200cشده (%)')),
                ('signoff_status', models.CharField(choices=[('pending', 'در انتظار امضا'), ('signed', 'امضا شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت امضا')),
                ('signoffs', models.JSONField(default=list, help_text='لیست: [{user_id, role, name, signed_at}]', verbose_name='امضاکنندگان')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='engine_05/closure_reports/', verbose_name='فایل گزارش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_closures', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure_report', to='intangible_assets.prioritizedproject', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'گزارش اختتام پروژه',
                'verbose_name_plural': 'گزارش\u200cهای اختتام پروژه',
            },
        ),
        migrations.AddIndex(
            model_name='prioritizedproject',
            index=models.Index(fields=['organization', 'approval_status'], name='intangible__organiz_f26cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='prioritizedproject',
            index=models.Index(fields=['rank'], name='intangible__rank_9f1b7e_idx'),
        ),
    ]
