# Generated by Django 5.0.6 on 2026-09-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0056_prioritizedproject_ganttschedule_developedornewasset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developedornewasset',
            name='asset_name',
            field=models.CharField(blank=True, help_text='مثلاً «سیستم حل اختلافات با تأمین\u200cکنندگان»', max_length=500, verbose_name='نام دارایی جدید'),
        ),
    ]
