# Generated by Django 5.0.6 on 2026-09-17 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_department_options_alter_organization_options_and_more'),
        ('intangible_assets', '0057_add_asset_name_to_developed_asset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VIAMUploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='viam/uploads/%Y/%m/')),
                ('original_name', models.CharField(max_length=500)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('image', 'تصویر'), ('video', 'ویدیو'), ('audio', 'صوت'), ('other', 'سایر')], max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=200)),
                ('file_size', models.BigIntegerField(default=0)),
                ('section', models.CharField(choices=[('strategic_planning', 'برنامه\u200cریزی و نقشه\u200cبرداری'), ('culture', 'جریان\u200cسازی و فرهنگ\u200cسازی'), ('empowerment', 'توانمندسازی و گواهی حرفه\u200cای'), ('performance', 'عملکرد، ممیزی و بلوغ')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viam_uploads', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viam_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فایل آپلودشده VIAM',
                'verbose_name_plural': 'فایل\u200cهای آپلودشده VIAM',
                'ordering': ['-created_at'],
            },
        ),
    ]
