# Generated by Django 5.0.6 on 2026-09-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0058_add_viam_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viamuploadedfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'اکسل'), ('powerpoint', 'پاورپوینت'), ('image', 'تصویر'), ('video', 'ویدیو'), ('audio', 'صوت'), ('database', 'دیتابیس'), ('archive', 'آرشیو'), ('code', 'کد'), ('other', 'سایر')], max_length=20),
        ),
    ]
