# Generated by Django 5.0.6 on 2026-09-20 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_department_options_alter_organization_options_and_more'),
        ('intangible_assets', '0059_add_more_file_types_to_viam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaturityComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد مؤلفه')),
                ('number', models.IntegerField(verbose_name='شماره مؤلفه')),
                ('name', models.CharField(max_length=200, verbose_name='نام مؤلفه')),
                ('domain', models.CharField(choices=[('hardware', 'سخت\u200cافزار (ساختار، حکمرانی و راهبری)'), ('brainware', 'مغزافزار (سرمایه انسانی، دانش و فرهنگ)'), ('orgware', 'سازمان\u200cافزار (فرآیند، مستندسازی و انطباق)'), ('software', 'نرم\u200cافزار (فناوری، داده و هوشمندی)')], max_length=20, verbose_name='بخش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'مؤلفه بلوغ',
                'verbose_name_plural': 'مؤلفه\u200cهای بلوغ',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MaturityWeightProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('base', 'پایه (متوازن)'), ('manufacturing', 'تولیدی'), ('service', 'خدماتی'), ('rto', 'RTO (پژوهش و فناوری)'), ('holding', 'هلدینگ صنعتی')], max_length=20, unique=True, verbose_name='نوع پروفایل')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('weight_hardware', models.FloatField(default=0.25, verbose_name='وزن سخت\u200cافزار')),
                ('weight_brainware', models.FloatField(default=0.25, verbose_name='وزن مغزافزار')),
                ('weight_orgware', models.FloatField(default=0.25, verbose_name='وزن سازمان\u200cافزار')),
                ('weight_software', models.FloatField(default=0.25, verbose_name='وزن نرم\u200cافزار')),
                ('component_weights', models.JSONField(default=dict, help_text='{"1": 0.20, "2": 0.35, ...}', verbose_name='وزن مؤلفه\u200cها')),
            ],
            options={
                'verbose_name': 'پروفایل وزنی',
                'verbose_name_plural': 'پروفایل\u200cهای وزنی',
            },
        ),
        migrations.CreateModel(
            name='MaturityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_total', models.FloatField(default=0, verbose_name='نمره کل (0-100)')),
                ('maturity_level', models.IntegerField(choices=[(1, 'سطح ۱: اولیه / بحرانی'), (2, 'سطح ۲: آغازین / موردی'), (3, 'سطح ۳: تعریف\u200cشده / استاندارد'), (4, 'سطح ۴: مدیریت\u200cشده / اندازه\u200cگیری\u200cشده'), (5, 'سطح ۵: بهینه / هوشمند')], default=1, verbose_name='سطح بلوغ')),
                ('score_hardware', models.FloatField(default=0, verbose_name='نمره سخت\u200cافزار')),
                ('score_brainware', models.FloatField(default=0, verbose_name='نمره مغزافزار')),
                ('score_orgware', models.FloatField(default=0, verbose_name='نمره سازمان\u200cافزار')),
                ('score_software', models.FloatField(default=0, verbose_name='نمره نرم\u200cافزار')),
                ('component_scores', models.JSONField(default=dict, help_text='{"1": 3.0, "2": 2.3, ...}', verbose_name='نمرات مؤلفه\u200cها')),
                ('gate_rules_status', models.JSONField(default=dict, help_text='{"G-A": false, "G-B": false, ...}', verbose_name='وضعیت قواعد دروازه\u200cای')),
                ('gap_analysis', models.JSONField(default=list, help_text='لیست اولویت\u200cدار اقدامات', verbose_name='تحلیل شکاف')),
                ('radar_data', models.JSONField(default=list, help_text='برای نمودار راداری', verbose_name='داده راداری')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('in_progress', 'در حال انجام'), ('calculated', 'محاسبه شده'), ('approved', 'تأیید شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maturity_assessments', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maturity_assessments', to='accounts.organization', verbose_name='سازمان')),
                ('weight_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='intangible_assets.maturityweightprofile', verbose_name='پروفایل وزنی')),
            ],
            options={
                'verbose_name': 'ارزیابی بلوغ',
                'verbose_name_plural': 'ارزیابی\u200cهای بلوغ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaturityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد پرسش')),
                ('number', models.IntegerField(verbose_name='شماره پرسش')),
                ('text', models.TextField(verbose_name='متن پرسش')),
                ('question_type', models.CharField(choices=[('measure', 'سنجش'), ('anchor', 'لنگر (اعتبارسنجی)')], default='measure', max_length=10, verbose_name='نوع پرسش')),
                ('anchor_level_3', models.TextField(blank=True, help_text='شاهد مورد نیاز برای نمره ۳', verbose_name='لنگر سطح ۳')),
                ('related_stage', models.CharField(blank=True, help_text='مرحله مدیریت دارایی نامشهود', max_length=50, verbose_name='مرحله مرتبط')),
                ('component', models.ForeignKey(blank=True, help_text='برای پرسش\u200cهای لنگر، خالی است', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='intangible_assets.maturitycomponent', verbose_name='مؤلفه')),
            ],
            options={
                'verbose_name': 'پرسش بلوغ',
                'verbose_name_plural': 'پرسش\u200cهای بلوغ',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MaturityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='نمره (1-5)')),
                ('has_evidence', models.BooleanField(default=False, verbose_name='شاهد دارد؟')),
                ('evidence_type', models.CharField(blank=True, choices=[('document', 'سند مصوب'), ('system', 'سامانه'), ('meeting', 'صورت\u200cجلسه'), ('data', 'داده عملکردی'), ('interview', 'مصاحبه'), ('other', 'سایر')], max_length=20, verbose_name='نوع شاهد')),
                ('evidence_description', models.TextField(blank=True, verbose_name='توضیح شاهد')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('responded_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ پاسخ')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='intangible_assets.maturityassessment', verbose_name='ارزیابی')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='intangible_assets.maturityquestion', verbose_name='پرسش')),
            ],
            options={
                'verbose_name': 'پاسخ بلوغ',
                'verbose_name_plural': 'پاسخ\u200cهای بلوغ',
                'unique_together': {('assessment', 'question')},
            },
        ),
    ]
