# Generated by Django 5.0.6 on 2026-09-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intangible_assets', '0060_add_maturity_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='maturityassessment',
            name='index',
            field=models.FloatField(default=0, verbose_name='شاخص IAMS (0-100)'),
        ),
        migrations.AlterField(
            model_name='maturityassessment',
            name='score_total',
            field=models.FloatField(default=0, verbose_name='نمره کل (0-5)'),
        ),
    ]
